# Generated by Django 3.2.2 on 2022-05-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('ssn', models.CharField(max_length=11)),
                ('staff_type', models.CharField(max_length=2)),
            ],
        ),
    ]
