# Generated by Django 3.2.2 on 2022-05-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_staffs_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='role',
            field=models.CharField(default='member', max_length=6),
        ),
    ]
