# Generated by Django 3.2.2 on 2022-05-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_alter_staffs_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='password',
            field=models.CharField(default='password001', max_length=200),
        ),
    ]
