# Generated by Django 3.2.2 on 2022-05-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='expire_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
