# Generated by Django 3.2.2 on 2022-05-18 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0001_initial'),
        ('customers', '0004_auto_20220518_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
                ('food', models.ManyToManyField(db_table='orders_and_foods', to='orders.Foods')),
                ('staffs', models.ManyToManyField(db_table='cookingstaff', to='staffs.Staffs')),
            ],
        ),
    ]
